name: SonarCloud

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Verify SONAR_TOKEN is present
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ -z "${SONAR_TOKEN}" ]; then
            echo "::warning::Missing secret SONAR_TOKEN. SonarCloud analysis will be skipped.";
          fi

      - name: Decide whether to run SonarCloud
        id: sonarcheck
        run: |
          ORG=$(grep -oP '(?<=<sonar.organization>).*?(?=</sonar.organization>)' pom.xml | head -n1 || true)
          KEY=$(grep -oP '(?<=<sonar.projectKey>).*?(?=</sonar.projectKey>)' pom.xml | head -n1 || true)
          if [ -z "$ORG" ] || [ -z "$KEY" ] || echo "$ORG$KEY" | grep -q 'YOUR_ORG_KEY'; then
            echo "SonarCloud not configured (org/projectKey). Skipping analysis.";
            echo "run=false" >> $GITHUB_OUTPUT
          else
            echo "run=true" >> $GITHUB_OUTPUT
          fi

      - name: Build, test and coverage (debug)
        run: |
          mvn -B -V -e -X verify

      - name: SonarCloud analyze (debug)
        if: steps.sonarcheck.outputs.run == 'true' && env.SONAR_TOKEN != ''
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B -e -X \
            -DskipTests \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.token=${SONAR_TOKEN}
